I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 11, in script
    with pixellatelink
  File "game/script.rpy", line 11, in <module>
    with pixellatelink
NameError: name 'pixellatelink' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 11, in script
    with pixellatelink
  File "C:\Users\evert\programa\renpy\renpy\ast.py", line 1671, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\evert\programa\renpy\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\evert\programa\renpy\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 11, in <module>
    with pixellatelink
NameError: name 'pixellatelink' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
QuickStart 1.0
Wed Jan 24 22:10:08 2024
